'use strict';
const path = require('path'); const process = require('process'); const marker = `${path.sep}cgi-bin${path.sep}`; const root = process.argv[1].slice(0, process.argv[1].indexOf(marker) + marker.length - 1);
const { http, InterfaceManager } = require(path.join(root, 'runtime.js'));
const method = String((process.env.get && process.env.get('REQUEST_METHOD')) || process.env.REQUEST_METHOD || ''); const factory = http.createFactory(() => new InterfaceManager({ cgiRoot: root }));
function done(status) { return (failure, value) => failure ? http.fail(failure) : http.reply(status, { ok: true, data: value }); }
function invalid(failure) { return Object.assign(new Error(failure && failure.message ? failure.message : 'DBus Method 요청이 잘못되었습니다.'), { code: 'DBUS_METHOD_INVALID', details: (failure && failure.details) || {} }); }
function requestFailure(failure) { return failure && failure.code === 'REQUEST_TOO_LARGE' ? failure : invalid(failure); }
function onlyFields(value, fields) { if (Object.keys(value).some((field) => !fields.includes(field))) throw http.requestError('DBus Method 요청에 알 수 없는 필드가 있습니다.'); return value; }
if (!factory.ok) http.fail(factory.error); else if (method === 'DELETE') { const query = http.readQuery(); if (!query.ok) http.fail(requestFailure(query.error)); else { try { onlyFields(query.value, ['interfaceId', 'methodId']); const value = http.requireStringFields(query.value, ['interfaceId', 'methodId']); factory.value.deleteMethod(value.interfaceId, value.methodId, done(200)); } catch (failure) { http.fail(failure && failure.code === 'REQUEST_INVALID' ? invalid(failure) : failure); } } } else if (method === 'POST' || method === 'PUT') { const body = http.readBody(); if (!body.ok) http.fail(requestFailure(body.error)); else { try { const payload = http.requireObject(body.value, 'DBus Method request'); if (method === 'POST') { onlyFields(payload, ['interfaceId', 'method']); http.requireStringFields(payload, ['interfaceId']); factory.value.createMethod(payload.interfaceId, http.requireObject(payload.method, 'method'), done(201)); } else { onlyFields(payload, ['interfaceId', 'methodId', 'method']); http.requireStringFields(payload, ['interfaceId', 'methodId']); factory.value.updateMethod(payload.interfaceId, payload.methodId, http.requireObject(payload.method, 'method'), done(200)); } } catch (failure) { http.fail(failure && failure.code === 'REQUEST_INVALID' ? invalid(failure) : failure); } } } else http.fail(Object.assign(new Error('지원하지 않는 요청 method입니다.'), { code: 'METHOD_NOT_ALLOWED' }), 405);
