'use strict';
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

function runCgi(script, options) {
  const settings = options || {};
  const program = `const env=process.env; process.env={...env,get:(name)=>env[name]}; process.stdin.read=()=>process.argv[2]||''; require(process.argv[1]);`;
  const result = childProcess.spawnSync(process.execPath, ['-e', program, script, settings.body || ''], { encoding: 'utf8', env: { ...process.env, REQUEST_METHOD: settings.method || 'GET', QUERY_STRING: settings.query || '' } });
  assert.equal(result.status, 0, result.stderr);
  const split = result.stdout.indexOf('\r\n\r\n');
  assert.notEqual(split, -1, result.stdout);
  return { status: Number(/Status: (\d+)/.exec(result.stdout.slice(0, split))[1]), payload: JSON.parse(result.stdout.slice(split + 4)) };
}
function iface() { return { schemaVersion: 1, id: 'cgi-device', name: 'CGI Device', origin: 'manual', builtIn: false, busType: 'system', destination: 'example.device', objectPath: '/example/device', interface: 'example.device.Status', methods: [] }; }
function createInterface() { const { id, ...value } = iface(); return value; }
function run() {
  const source = path.resolve(__dirname, '..'); const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'neo-dbus-interface-cgi-')); const root = path.join(temporary, 'cgi-bin');
  try {
    fs.cpSync(source, root, { recursive: true });
    fs.rmSync(path.join(root, 'interfaces.d'), { recursive: true, force: true });
    fs.mkdirSync(path.join(root, 'interfaces.d'), { recursive: true });
    fs.mkdirSync(path.join(root, 'conf.d', 'interfaces'), { recursive: true });
    let response = runCgi(path.join(root, 'api', 'dbus-interface', 'list.js'));
    assert.equal(response.status, 200); assert.deepEqual(response.payload, { ok: true, data: [] });
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'POST', body: '[]' });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'POST', body: 'x'.repeat(512 * 1024 + 1) });
    assert.equal(response.status, 413); assert.equal(response.payload.code, 'REQUEST_TOO_LARGE');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'POST', body: JSON.stringify({ interfaces: [iface()] }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'POST', body: JSON.stringify({ ...createInterface(), unexpected: true }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { query: 'id=cgi-device' });
    assert.equal(response.status, 404); assert.equal(response.payload.code, 'DBUS_INTERFACE_NOT_FOUND');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { query: 'id=Bad_Interface' });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'));
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { query: 'id=cgi-device&extra=true' });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { query: `id=${'a'.repeat(128 * 1024)}` });
    assert.equal(response.status, 413); assert.equal(response.payload.code, 'REQUEST_TOO_LARGE');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'POST', body: JSON.stringify({ ...createInterface(), id: 'client-id' }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'POST', body: JSON.stringify({ ...createInterface(), name: '' }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'POST', body: JSON.stringify(createInterface()) });
    assert.equal(response.status, 201); assert.equal(response.payload.data.id, 'cgi-device');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'PUT', query: 'discover=false', body: JSON.stringify(iface()) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'PUT', query: 'discover=true', body: JSON.stringify(iface()) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'PUT', body: JSON.stringify({ ...iface(), id: 'Bad_Interface' }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'PUT', body: JSON.stringify({ ...iface(), unexpected: true }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'POST', body: JSON.stringify({ interfaceId: 'cgi-device', method: [] }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'POST', body: JSON.stringify({ interfaceId: 'Bad_Interface', method: { id: 'read', source: 'manual', member: 'Read', inputs: [], outputs: [] } }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'POST', body: JSON.stringify({ interfaceId: 'cgi-device', method: { id: 'Bad_Method', source: 'manual', member: 'Read', inputs: [], outputs: [] } }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'POST', body: 'x'.repeat(512 * 1024 + 1) });
    assert.equal(response.status, 413); assert.equal(response.payload.code, 'REQUEST_TOO_LARGE');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'POST', body: JSON.stringify({ interfaceId: 'cgi-device', method: { id: 'outer-extra', source: 'manual', member: 'OuterExtra', inputs: [], outputs: [] }, extra: true }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'POST', body: JSON.stringify({ interfaceId: 'cgi-device', methodId: 'outer-extra', method: { id: 'outer-extra', source: 'manual', member: 'OuterExtra', inputs: [], outputs: [] } }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'POST', body: JSON.stringify({ interfaceId: 'cgi-device', method: { id: 'unexpected', source: 'manual', member: 'Unexpected', inputs: [], outputs: [], unexpected: true } }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { query: 'id=cgi-device' });
    assert.equal(response.status, 200); assert.equal(response.payload.data.interface.methods.length, 0);
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'POST', body: JSON.stringify({ interfaceId: 'cgi-device', method: { id: 'read', source: 'manual', member: 'Read', inputs: [], outputs: [] } }) });
    assert.equal(response.status, 201); assert.equal(response.payload.data.member, 'Read');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'PUT', body: JSON.stringify({ interfaceId: 'Bad_Interface', methodId: 'read', method: { id: 'read', source: 'manual', member: 'Changed', inputs: [], outputs: [] } }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'PUT', body: JSON.stringify({ interfaceId: 'cgi-device', methodId: 'Bad_Method', method: { id: 'Bad_Method', source: 'manual', member: 'Changed', inputs: [], outputs: [] } }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'PUT', body: JSON.stringify({ interfaceId: 'cgi-device', methodId: 'read', method: { id: 'read', source: 'manual', member: 'Changed', inputs: [], outputs: [], unexpected: true } }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'PUT', body: JSON.stringify({ interfaceId: 'cgi-device', method: { id: 'read', source: 'manual', member: 'Changed', inputs: [], outputs: [] } }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'PUT', body: JSON.stringify({ interfaceId: 'cgi-device', methodId: 'read', method: { id: 'read', source: 'manual', member: 'Changed', inputs: [], outputs: [] }, extra: true }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'PUT', body: JSON.stringify({ interfaceId: 'cgi-device', methodId: 'read', method: { source: 'manual', member: 'Changed', inputs: [], outputs: [] } }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'PUT', body: JSON.stringify({ interfaceId: 'cgi-device', methodId: 'read', method: { id: 'other', source: 'manual', member: 'Changed', inputs: [], outputs: [] } }) });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    fs.writeFileSync(path.join(root, 'conf.d', 'interface-review-required.json'), `${JSON.stringify([{
      interfaceId: 'cgi-device', methodId: 'read', reason: 'signature-changed',
    }])}\n`);
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'PUT', body: JSON.stringify({ ...iface(), methods: [{ id: 'read', source: 'manual', member: 'ReviewBypass', inputs: [], outputs: [] }] }) });
    assert.equal(response.status, 200); assert.equal(response.payload.data.methods[0].member, 'ReviewBypass');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'PUT', body: JSON.stringify({ interfaceId: 'cgi-device', methodId: 'read', method: { id: 'read', source: 'manual', member: 'Changed', inputs: [], outputs: [] } }) });
    assert.equal(response.status, 200); assert.equal(response.payload.data.member, 'Changed');
    fs.writeFileSync(path.join(root, 'conf.d', 'interface-review-required.json'), '{not-json}\n');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'PUT', body: JSON.stringify({ ...iface(), destination: 'example.device.Restored', methods: [{ id: 'read', source: 'manual', member: 'ChangedWhileLegacyFileExists', inputs: [], outputs: [] }] }) });
    assert.equal(response.status, 200); assert.equal(response.payload.data.methods[0].member, 'ChangedWhileLegacyFileExists');
    fs.unlinkSync(path.join(root, 'conf.d', 'interface-review-required.json'));
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'PUT', body: JSON.stringify({ ...iface(), interface: 'example.device.Updated', methods: [{ id: 'read', source: 'manual', member: 'ChangedWithoutReview', inputs: [], outputs: [] }] }) });
    assert.equal(response.status, 200); assert.equal(response.payload.data.methods[0].member, 'ChangedWithoutReview');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { query: 'id=cgi-device' });
    assert.equal(response.status, 200); assert.equal(response.payload.data.interface.methods[0].member, 'ChangedWithoutReview');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'DELETE', query: 'interfaceId=cgi-device' });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'DELETE', query: 'interfaceId=Bad_Interface&methodId=read' });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'DELETE', query: 'interfaceId=cgi-device&methodId=Bad_Method' });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'DELETE', query: 'interfaceId=cgi-device&methodId=read&extra=true' });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_METHOD_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'DELETE', query: `interfaceId=cgi-device&methodId=${'a'.repeat(128 * 1024)}` });
    assert.equal(response.status, 413); assert.equal(response.payload.code, 'REQUEST_TOO_LARGE');
    response = runCgi(path.join(root, 'api', 'dbus-method.js'), { method: 'DELETE', query: 'interfaceId=cgi-device&methodId=read' });
    assert.equal(response.status, 200); assert.deepEqual(response.payload.data, { interfaceId: 'cgi-device', methodId: 'read' });
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'DELETE', query: 'id=cgi-device' });
    assert.equal(response.status, 200); assert.deepEqual(response.payload.data, { id: 'cgi-device' });
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'DELETE', query: 'id=cgi-device&extra=true' });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'DELETE', query: 'id=Bad_Interface' });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
    response = runCgi(path.join(root, 'api', 'dbus-interface.js'), { method: 'DELETE' });
    assert.equal(response.status, 400); assert.equal(response.payload.code, 'DBUS_INTERFACE_INVALID');
  } finally { fs.rmSync(temporary, { recursive: true, force: true }); }
}
run(); console.log('DBus Interface/Method CGI API: ok');
